#!/bin/bash
set -euo pipefail

convert -size 100x300 xc:"#e8c89c" menu.png
convert menu.png -fill none -stroke black -strokewidth 2 -draw "rectangle 0,0 100,50" menu.png
convert menu.png -fill none -stroke black -strokewidth 2 -draw "rectangle 0,0 100,100" menu.png
convert menu.png -fill none -stroke black -strokewidth 2 -draw "rectangle 0,0 100,150" menu.png
convert menu.png -fill none -stroke black -strokewidth 2 -draw "rectangle 0,0 100,200" menu.png
convert menu.png -fill none -stroke black -strokewidth 2 -draw "rectangle 0,0 100,250" menu.png
convert menu.png -fill none -stroke black -strokewidth 2 -draw "rectangle 0,0 100,300" menu.png
